// This file is automatically generated. Do not edit it directly.
// SINGLETON-PATCHED VERSION: Prevents multiple GoTrueClient instances

import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

const SUPABASE_URL = "https://uxyvhqtwkutstihtxdsv.supabase.co"
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4eXZocXR3a3V0c3RpaHR4ZHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MzY0ODksImV4cCI6MjA2MTAxMjQ4OX0.oR-Jl_hJIVgehVr5J9oEB8WqxZCXREXY07cwFoW5COE"

// Singleton guard
declare global {
  interface Window {
    __supabase_singleton?: ReturnType<typeof createClient<Database>>
  }
}

// Create or reuse singleton instance
const getSupabaseClient = () => {
  if (typeof window !== 'undefined') {
    if (!window.__supabase_singleton) {
      window.__supabase_singleton = createClient<Database>(
        SUPABASE_URL, 
        SUPABASE_PUBLISHABLE_KEY,
        {
          auth: {
            storage: localStorage,
            autoRefreshToken: true,
            persistSession: true
          }
        }
      )
      console.log('🔧 Created singleton Supabase client')
    }
    return window.__supabase_singleton
  }
  
  // Server-side fallback
  return createClient<Database>(
    SUPABASE_URL, 
    SUPABASE_PUBLISHABLE_KEY,
    {
      auth: {
        storage: localStorage,
        autoRefreshToken: true,
        persistSession: true
      }
    }
  )
}

export const supabase = getSupabaseClient()

// Keep the original comment for reference
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
